sudo: required
services: 
    - docker

before_install:
    - docker build -t repo_test -f Dockerfile.dev .

script: 
    - docker run -e CI=true repo_test npm run test

deploy: 
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "Udemy Docker Kubernetes"
    env: "UdemyDockerKubernetes-env"
    bucket_name: "elasticbeanstalk-us-west-2-834524383197"
    bucket_path: "Udemy Docker Kubernetes"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_ACCESS_KEY